"""
Function: generate a ppt file based on the figures' directory and the given abnormal values' list
Author: Xinran Wang
Date: 07/22/2020
"""

from os import listdir
from os.path import join, basename
from re import findall
import pptx
from pptx.util import Inches, Pt
from pptx.enum.text import PP_PARAGRAPH_ALIGNMENT
from change_line_test import *


def generate_ppt(fig_path, abnormal_lists):
    """
    Generate the powerpoint, each page has one figure; for the merged dataframe, the outlier interval will also be listed on the powerpoint; the powerpoint will be saved in the same directory as this project
    :param fig_path: the absolute path of the folder containing all the figures drawn
    :param abnormal_lists: a list containing several lists, each list contains intervals generated by convert_t_to_interval function
    :return: None
    """
    index = 0
    # set as reading png file, subject to change (?)
    pic_files = [join(fig_path, fn) for fn in listdir(fig_path) if fn.endswith(".png")]

    ppt_file = pptx.Presentation()
    ppt_file.slide_width = Inches(16)
    ppt_file.slide_height = Inches(9)
    for fn in pic_files:
        slide = ppt_file.slides.add_slide(ppt_file.slide_layouts[6])
        txt = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), ppt_file.slide_width, Inches(5))
        p = txt.text_frame.add_paragraph()
        p.text = basename(fn)
        slide.shapes.add_picture(fn, Inches(0), Inches(1.5), Inches(16), Inches(6.4))

        pic_name = basename(fn)
        splitted_name = pic_name.split("-")
        data_type = splitted_name[2]

        if "Merged" in pic_name:
            abnormal_text, lines = change_lines(abnormal_lists[index])

            slide = ppt_file.slides.add_slide(ppt_file.slide_layouts[6])
            abnormal = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), ppt_file.slide_width, Inches(5))
            para = abnormal.text_frame.add_paragraph()
            para.text = "Potential abnormal frame time intervals in original data:" + "\n" + abnormal_text

            index += 1
        p.alignment = PP_PARAGRAPH_ALIGNMENT.LEFT
        p.font.name = "Times New Roman"
        p.font.size = Pt(25)
    ppt_file.save("Reinjection.pptx")
