"""
Function: helps to convert a very long list variable into a string with multiple lines that can be fit into the text box of powerpoint
Author: Xinran Wang
Date: 07/23/2020
"""

def change_lines(range_list, width = 90):
    """
    convert a very long list into a string with multiple lines
    :param range_list: the timestamp range list generated by convert_t_to_interval function
    :param width: the max width of the text box, used to limit the line changing of text
    :return: a sting with multiple lines, and the line No.
    """
    output = ""
    line_number = 0
    length_count = 1
    for item in range_list:
        item_length = len(item)
        if length_count + item_length > width:
            length_count = 0
            line_number += 1
            output += item + ", \n"
        else:
            length_count += item_length
            output += item + ", "
    return output.strip(", "), line_number+1
